import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

const OUTPUT_DIR = "./invoices";

/**
 * Generates a PDF invoice for a job.
 * In production, upload this to IPFS/S3 and store the URL.
 */
export async function generateInvoicePDF(invoice) {
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  const filename = `INV-${invoice.invoiceNumber}.pdf`;
  const filepath = path.join(OUTPUT_DIR, filename);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const stream = fs.createWriteStream(filepath);

    doc.pipe(stream);

    // Header
    doc
      .fontSize(24)
      .font("Helvetica-Bold")
      .text("FreelanceArc", 50, 50)
      .fontSize(10)
      .font("Helvetica")
      .fillColor("#666")
      .text("Built on Arc — USDC Payments", 50, 80)
      .moveDown(2);

    // Invoice title
    doc
      .fillColor("#000")
      .fontSize(18)
      .font("Helvetica-Bold")
      .text(`INVOICE #INV-${invoice.invoiceNumber}`, { align: "right" })
      .fontSize(10)
      .font("Helvetica")
      .fillColor("#666")
      .text(`Date: ${new Date(invoice.createdAt).toLocaleDateString()}`, { align: "right" })
      .text(`Network: Arc Testnet (Chain ID: 5042002)`, { align: "right" })
      .moveDown(2);

    // Divider
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#e0e0e0").stroke().moveDown(1);

    // Parties
    doc
      .fillColor("#000")
      .fontSize(11)
      .font("Helvetica-Bold")
      .text("Bill To (Client):")
      .font("Helvetica")
      .fontSize(10)
      .fillColor("#333")
      .text(invoice.client || "—")
      .moveDown(1);

    if (invoice.freelancer) {
      doc
        .font("Helvetica-Bold")
        .fontSize(11)
        .fillColor("#000")
        .text("Bill From (Freelancer):")
        .font("Helvetica")
        .fontSize(10)
        .fillColor("#333")
        .text(invoice.freelancer)
        .moveDown(1);
    }

    // Job details
    doc
      .font("Helvetica-Bold")
      .fillColor("#000")
      .text("Job Title:")
      .font("Helvetica")
      .fillColor("#333")
      .text(invoice.title || `Job #${invoice.jobId}`)
      .moveDown(1);

    // Milestones table
    if (invoice.milestones?.length > 0) {
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#e0e0e0").stroke().moveDown(0.5);

      doc
        .font("Helvetica-Bold")
        .fillColor("#000")
        .fontSize(11)
        .text("Milestones", 50, doc.y)
        .moveDown(0.5);

      invoice.milestones.forEach((ms, i) => {
        const amount = (Number(ms.amount) / 1_000_000).toFixed(2);
        doc
          .font("Helvetica")
          .fontSize(10)
          .fillColor("#333")
          .text(`${i + 1}. ${ms.description}`, 60, doc.y, { width: 380 })
          .text(`${amount} USDC`, 0, doc.y - doc.currentLineHeight(), { align: "right" })
          .moveDown(0.3);
      });
    }

    doc.moveTo(50, doc.y + 10).lineTo(545, doc.y + 10).strokeColor("#e0e0e0").stroke();
    doc.moveDown(1.5);

    // Total
    const total = (Number(invoice.amountUsdc) / 1_000_000).toFixed(2);
    doc
      .font("Helvetica-Bold")
      .fontSize(13)
      .fillColor("#000")
      .text(`Total: ${total} USDC`, { align: "right" })
      .moveDown(0.3)
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#999")
      .text("USDC on Arc Testnet (ERC-20, 6 decimals)", { align: "right" })
      .moveDown(2);

    // On-chain reference
    doc
      .font("Helvetica-Bold")
      .fontSize(10)
      .fillColor("#000")
      .text("On-Chain Reference")
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#666")
      .text(`Job ID: ${invoice.jobId}`)
      .text(`Tx Hash: ${invoice.txHash || "Pending"}`)
      .text(`Explorer: https://testnet.arcscan.app`);

    // Footer
    doc
      .fontSize(8)
      .fillColor("#aaa")
      .text("Generated by FreelanceArc · Powered by Arc (arc.io) · USDC by Circle", 50, 780, {
        align: "center",
        width: 495,
      });

    doc.end();

    stream.on("finish", () => {
      resolve(filepath);
    });
    stream.on("error", reject);
  });
}
